### ISSUE TITLE
Provide a way to change the colormap

### ISSUE THREAD

**Issue by huaracheguarache** [metno/sea-ice-index-viz#11]
It can be useful to change the colormap to a different colorscale.

- Sequential: to give a quick impression of how the sea ice extent and area have changed due to climate change. The first year in the data starts at one end of the colorscale while the last year ends at the other end.
- Scrambled: this type of colorscale is useful when you want to compare a limited number of individual years and while being able to differentiate between them on the graph.

**Comment by huaracheguarache** [comment]
Always having the current year in black will mess with the CVD friendliness of the colorscales, I'm not sure that's such a good idea.

**Comment by TomLav** [comment]
I now see your comment about the current year. I'd like to suggest that we enforce "black and thicker for the current year" for all the available color schemes. It messes maybe a bit with CVD but black is one of the colors that are well distinguishable and we make the curve thicker already. I think in the future we could add a "CVD" colorscheme with no compromise.
