### ISSUE TITLE
MONTHLY : add the possibility to plot YEARLY averages

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#111]
It could be interesting to plot timeseries of yearly average values in the same service as we have our monthly visualization.

There are some challenges:

- At present the sea-ice index product does not have yearly indexes, so these must be computed by the visualization tool from the monthly values.
- For some years (specifically 1986 and 1987, and the current year) we are missing monthly values and the yearly average cannot be computed as easily. Options are 1) to not plot these years, and 2) to interpolate missing months before the computation of yearly averages.

As far as the UI is concerned, we could have a new glyph "Yearly" that triggers plotting the yearly average (and its trend line). This can be in addition to 1 or several monthly curves.

what do you think @signeaa ?

**Comment by signeaa** [comment]
I like the idea to add a yearly time series. I think we should do linear interpolation over missing months. Then 1978 is out I guess... And the latest-year can only be plotted when we enter a new year.
An idea would be to 
1. plot the annual mean values with a dots and thin line between years.
2. Add (optional as the climotologies) the 0/100% percentiles in shades around the line.
3. add trend line

**Comment by TomLav** [comment]
Close as wontfix from the visualization side.
