### ISSUE TITLE
Adjust y-axis for SH regions

### ISSUE THREAD

**Issue by signeaa** [metno/sea-ice-index-viz#114]
All the SH sub-regions (except Weddell) get an overlap between minimum period lines and the description text. Should we adjust the default y-axis to avoid this? To include negative values on y-axis without labelling them could be a solution?

**Comment by TomLav** [comment]
@huaracheguarache investigate if negative ymin (not labelled) are easy to get to with bokeh.

Also, if y=0 is in the plot region, add a y=0 stippled axis.

**Comment by huaracheguarache** [comment]
How much of an offset we need will depend on the screen size of the client that is viewing the visualisation. I'll need to figure out how to account for this.
