### ISSUE TITLE
In figure title and text, use vX.Y instead of vXpY

### ISSUE THREAD

**Issue by signeaa** [metno/sea-ice-index-viz#124]
Today, the title contains "v2p2". It should rather be "v2.2"

**Comment by huaracheguarache** [comment]
@signeaa @TomLav Is it possible to change the file generation process such that the version attribute of the dataset and the title contains v2.2 instead of v2p2? That would be the best way to solve this if there is no reason to keep using the vxpx version scheme.

**Comment by TomLav** [comment]
Michael, can you implement?

**Comment by huaracheguarache** [comment]
Will do. I'll commit this together with the parquet precalculating functionality.

**Comment by TomLav** [comment]
What is the status for this, @signeaa ? Is this solved and can we close the issue?

**Comment by signeaa** [comment]
It is not solved in the version available online

**Comment by TomLav** [comment]
depends on #125
