### ISSUE TITLE
information on using SIC v3

### ISSUE THREAD

**Issue by signeaa** [metno/sea-ice-index-viz#125]
Vedrørende forklarende text i venstre nedre hjørne
Skulle vi erstatte andre linje 
"v2.2 EUMETSAT...." 
med setning som brukes på de statiske figurer 
"Data: Derived from OSI SAF Sea Ice Concentration CDRs v3" 

Dette for å synliggjøre at v2.2 benytter SIC v3 data

**Comment by TomLav** [comment]
Det er god idée. @huaracheguarache, kan du implementere denne?

**Comment by huaracheguarache** [comment]
Vil dere at jeg skal fjerne linjen med "v2.2 EUMETSAT" fullstendig, eller vil dere at jeg skal erstatte all teksten i det interaktive plottet slik at den matcher den som er i de statiske bildene (se nede)?

![osisaf_sh_sie_daily-all](https://github.com/metno/sea-ice-index-viz/assets/33153877/bb586f8d-06de-40d3-95f6-9f43889f2f87)

Jeg kan erstatte alt, men "Latest monthly data: ..." må nok beholdes.

![bokeh_plot](https://github.com/metno/sea-ice-index-viz/assets/33153877/90f91067-af50-4854-8db2-78c4ffd40c40)

**Comment by signeaa** [comment]
Jeg liker best teksten på statiske figurer (med unntak av last data point som kan bli). Men da vil evt kreditering til ESA CCI forsvinde fra dynamisk. Men kanskje vi skal re-tenke ut al tekst på figurene. Er kanskje litt overkill med "EUMETSAT" og "OSI SAF" nevnt 3-4 ganger på de dynamiske figurer? 
Jeg ville også forsimplet tittel - slik som statisk figur.
Her har Thomas meninger.

**Comment by signeaa** [comment]
@TomLav tror status er at du må melde ut om "with R&D input from ESA CCI" kan tas helt bort. Dette skjer hvis vi erstatter
"v2.2 EUMETSAT...."
med setning som brukes på de statiske figurer
"Data: Derived from OSI SAF Sea Ice Concentration CDRs v3"

Og en tilbakemelding på om tittel kan forsimples. Kan vel egentlig bare være " <REgion> Sea Ice Extent v2.2" tenker jeg... EUMETSAT og OSI SAF står allerede i teksten i venstre hjørne. 

Hva tenker dere?

**Comment by TomLav** [comment]
I de statiske figurene har vi "OSI SAF data with R&D input from ESA CCI" i høyre margin, utenfor plot area (se under). Kan vi få til noe slik med bokeh, @huaracheguarache ?

![image](https://github.com/metno/sea-ice-index-viz/assets/9883832/29226c5f-940d-4a11-bb66-7e80965375d3)

Jeg er enig i at tittelen kan forenkles, e.g. til "Daily Northern Hemisphere Sea Ice Extent v2.2"

**Comment by signeaa** [comment]
Hvis vi tar med den setning i høyre margin, da trenger vi kanskje ikke Source-linjen i venstre hjørne? Kanskje vi kan rett og slet erstatte Source-linje med "OSI SAF data with R&D input from ESA CCI".
Jeg synes vi må begrense litt hvor mange ganger vi i en figur nevne at det er OSISAF data...

**Comment by TomLav** [comment]
Also add:

Data: "Derived from OSI SAF Sea Ice Concentration CDRs v3"

T.
