### ISSUE TITLE
order of ranking should be the same all over

### ISSUE THREAD

**Issue by signeaa** [metno/sea-ice-index-viz#128]
Up for discussion.
But I think "1" should always refer to record low. Both for daily / monthly values and for the min and max dots. And vice versa with "44" (even though this is changing every year).

Today, the max-dots have reversed order with "1" indicating a record high. I see the point of this. But I think it is confusing. 

Any other perspectives or opinions on this?

**Comment by TomLav** [comment]
I agree with you, Signe. I think we discussed this in the past.
@huaracheguarache would this be an easy fix?

**Comment by huaracheguarache** [comment]
Yes, this is an easy fix. I'll get this done once I reinstall an OS on my laptop (attempting to install a Fedora pre-release version was a bad idea).
