### ISSUE TITLE
Handle two page layouts (landscape and portrait).

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#13]
I would suggest that we work with two page formats: landscape (the one we have now) and portrait (legend and controls below the plot). For now we could add a button that switches between the two formats. Later the switch could be automated following the aspect ratio of the window.

**Comment by TomLav** [comment]
![image](https://user-images.githubusercontent.com/9883832/183423580-a0d9040c-9819-4721-8a90-4d54e7a806a2.png)

I hear what you say that Bokeh doesn't allow for the plot legend to be placed below the plot area, but could the other part of the UI (circled in red in the screenshot above) be positioned below the plot area, as a first step?

**Comment by epifanio** [comment]
adding buttons to hide/show the widget tools could be useful as well

**Comment by TomLav** [comment]
Close for now, this is not the priority.
