### ISSUE TITLE
Include two new regional index - drml & trol

### ISSUE THREAD

**Issue by signeaa** [metno/sea-ice-index-viz#135]
We have two new regional indexes in the operational run. The drml=Dronning Maud Land and trol= Troll station. 
Could we include these two in the interactive plots? Data are found same place as the other regions - 
/lustre/storeB/project/metproduction/products/osisaf/output/ice/extent/figs_v2p2

**Comment by huaracheguarache** [comment]
Is it possible to move the data for these regions into the main Thredds sea ice index directory? I would like to fetch all of the data from the same location.

**Comment by signeaa** [comment]
På Lustre ligger de her:

- /lustre/storeB/project/metproduction/products/osisaf/output/ice/extent/figs_v2p2  [for ref perioden 1981-2010]
- /lustre/storeA/project/fou/fd/operational/extent_2020/figs_v2p2/  [for ref perioden 1991-2020]

Usikker hvoerdan de kommer til THREDDS...
