### ISSUE TITLE
It should be clear when work is in progress

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#15]
The tool sometimes takes time to update the plot (e.g. when switching all years to a new area). This is not a big deal if the user gets the information that things are happening (i.e. the website is not broken, but this request is taking time). It could be changing the pointer to a wheel, or write something on the screen.

Not sure if this is something for the Bokeh app or rather for the website that embeds the app.

**Comment by huaracheguarache** [comment]
Bokeh currently doesn't offer any way to indicate that it's loading/calculating data, but the Panel package does. I'll see if I can figure out a way to use that in my script.

**Comment by epifanio** [comment]
You may be able to use panel by wrapping the bokeh app as a panel widget, see https://panel.holoviz.org/reference/panes/Bokeh.html
then use `panel serve` the same way as we use `bokeh serve`

**Comment by huaracheguarache** [comment]
@epifanio Thanks for the tip! I wrapped things with panel and added a loading indicator in #54. Everything's working for me locally, but for some reason it didn't work when I tested it on the mybinder instance. Do you know why that's the case?
