### ISSUE TITLE
Start a new dataviz : monthly timeseries

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#17]
** Only when we are done with all the tasks for the daily curves **

We started with the daily sea-ice extent/area curves.

We also have the monthly timeseries that could benefit from the interactive visualization.

The task is to make interactive visualization of the monthly data that are here (url for NH SIE):
https://thredds.met.no/thredds/catalog/osisaf/met.no/ice/index/v2p1/nh/catalog.html?dataset=osisaf/met.no/ice/index/v2p1/nh/osisaf_nh_sie_monthly.nc

First we want to reproduce this type of graph:
https://osisaf-hl.met.no/archive/osisaf/sea-ice-index/v2p1/nh/en/osisaf_nh_sie_monthly-prev.png

This is where the current implementation for the static images is:
https://gitlab.met.no/amelien/osisaf-ice-extent/-/blob/master/pysie/pysie/plots.py#L315

Thus, the interface needs (minimum) 1) choice of area, 2) choice of index (SIE/SIA), 3) choice of month. We want to always plot the trend line (no option to remove it). We want the trend values (XX thousands $km^2 / year$ and XX%/dec) to be written in the plot area, potentially within a box, but the arrow is maybe not necessary. The relative trend (XX%/dec) depends on the climatology period, so we also need to be able to select between the two periods.

The hover tool can show:
- Date (e.g. May 2020)
- Value (e.g. 14.234 $mill km^2$)
- Rank (e.g. 2 if this is the second lowest May in all the timeseries).

No need to change colors. But we should be able to select the language when we have done it.

We want a new app (not to clutter the "daily app"). But we also want to re-use the code that can be re-used (e.g. the buttons, the language support). Thus I guess we want a new "main.py" (maine_monthly.py) that includes a module (common.py) where code that is common to monthly and daily is stored. We can have two notebooks as well (that both use the common.py).

**Comment by signeaa** [comment]
Just a comment. Could we have "this year's" value as an option to add despite the month is not completed? For this to work we could add in the plot the text for "date plotted"

**Comment by huaracheguarache** [comment]
As discussed with @TomLav, the next points on the agenda are:

* Figure out how to insert the information about the absolute and relative trend inside a bubble in the plot area.
* Make sure that there is more padding at the top and bottom of the graphs. In addition to this, find a way to make the span consistent across the graphs to make it possible to visually discern which index and area combinations have small and large trends.
* Investigate merging the functionality of the monthly plots (e.g. https://osisaf-hl.met.no/archive/osisaf/sea-ice-index/v2p1/nh/en/osisaf_nh_sie_monthly-curr.png) and the September/March plots (e.g. https://osisaf-hl.met.no/archive/osisaf/sea-ice-index/v2p1/nh/en/osisaf_nh_sie_monthly-all.png). We want to make it possible to select all of the months of the year for the user.

**Comment by TomLav** [comment]
Done. We use other issues to add functionalities.
