### ISSUE TITLE
Add some info in the plot area

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#18]
Take a look at:
https://osisaf-hl.met.no/archive/osisaf/sea-ice-index/v2p1/nh/en/osisaf_nh_sie_daily-2years.png

We would like to have text and logos in the plot area, at minimum:
"EUMETSAT OSI SAF data with R&D input from ESA CCI"
"v2p1"
The indication of the climatology period and min/max period (but the percentiles are defined in the legend).
An indication of the date of the most recent data point that is plotted.
The sentence "Source: EUMETSAT OSI SAF (https://osi-saf.eumetsat.int)"

We do not need the "Graph generated..." sentence.

**Comment by huaracheguarache** [comment]
For now I've merged a pull request that partially resolves this issue. What's still missing is a label indicating the climatology and min/max period, and also the date of the most resent data point. I want to place these in the upper part of the plot, right under the upper frame. However, Bokeh doesn't support negative relative positions in a way that allows me to do this (see https://github.com/bokeh/bokeh/issues/12215).

**Comment by TomLav** [comment]
Two ideas:
1) the climatology period label should be dynamic with the user choice;
2) add a line "last data point: YYYY-MM-DD" to print the date of the most recent data point in the thredds file (to detect when new data was not loaded as it should);
