### ISSUE TITLE
New menu for zooming the x-axis

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#21]
Add a drop-down menu "Time range" that defaults to "Year", but also offers:

- "Zoom" (2 months centered on the current date)
- "Min extent" 
- "Max extent"

Min and Max Extent can be 2-months periods centered on Sept and March (for NH and its sub-regions) and Feb and August (for SH and its subregions).

When one of these is selected, the xlim() of the plot area is changed. The ylim for "Year" (Jan-Dec) can still be (0, ymax) but the ylim for the others can be set dynamically by bokeh.

The above is more like a suggestion. If you have other ideas around this concept, please test them.

**Comment by huaracheguarache** [comment]
I've managed to create a zoom dropdown menu shortcut. Right now it only zooms in on the specific x-range, I've yet to find a way to do the same for the y-range. I'll merge my pull request and reopen this issue so that you can provide your thoughts on the y-range issue.
