### ISSUE TITLE
Text on the plots should be "dynamic"

### ISSUE THREAD

**Issue by signeaa** [metno/sea-ice-index-viz#71]
In the left lower corner we have information text. First line is:
"Median and percentiles for XXX, min/max for YYYY"
Should this line be flexible for what is shown. I see three cases:
1. When "Show all" then the sentence can be as it is today.
2. When Min/Max is not included in the plot, then this last part of the sentence should be removed
3. When Climatology is not included in the plot, then this first part of the sentence should be removed
Also, "percentiles" is not sufficient to label both the 25/75 and the 10/90, is it?

**Comment by huaracheguarache** [comment]
I'm wondering how this should fit in with the new decadal climatology plots that have been added. What would be the right way to do this if for example a user plots both the 25/75, 10/90 climatology and the new 0/100 decadal climatology?

**Comment by signeaa** [comment]
Tricky. 
The decadal plots in fact show **all** within this decade. For instance, show all temporal variability exactly as they are. So the labels to the right might be sufficient here.
For the 30years climatology, this is a bit different. Here are shown the 25/75 and 10/90 percentiles, and this information is maybe more important to specify with text as is done in the left corner. 
So, one solution could be to not "text" the decades but only the climatology.

However, this text in the left corner should be dynamic according to what has been activated. The first line needs to change if either Min/Max or Climatology are deactivated. Right?

Other solution may also work :)
