### ISSUE TITLE
More distinct colors for selected years

### ISSUE THREAD

**Issue by signeaa** [metno/sea-ice-index-viz#72]
Today, the colormaps "BatlowS" gives the opportunity to plot with a none-continuous colormap. However, when I want to plot a few selected years I would have loved to get these very distinctive colors that are approved for color blindness. So that we get something similar to today's daily-2years and daily-5years, etc (fx https://osisaf-hl.met.no/archive/osisaf/sea-ice-index/v2p1/nh/en/osisaf_nh_sie_daily-2years.png)

**Comment by TomLav** [comment]
We create a new Custom colour palette inspired from the 20 distinct colors (with repetition). The first few colours are those we want for the "2 years" and "5 years" shortcuts: (from Signe: for 2years, it will be the yellow and the blue. For 5years it will be yellow, blue, red, orange, lavender... etc).
