### ISSUE TITLE
Add point for min and max

### ISSUE THREAD

**Issue by signeaa** [metno/sea-ice-index-viz#77]
An idea just
To include the option to add the minimas and maximas per year as a dot. Would be great when approaching an extramum to see previous years' date/value. Dot colours follow the year colours.
Maybe it should be an option in the "Index" menu, e.g.: "min/max Sea Ice Extent" - which then only plots the dots....

**Comment by TomLav** [comment]
Hei Signe,
That's interesting ! We have a question. Do you want that:
- The user sees all the dots (for 40+ years), OR
- The user sees the dots only for the lines/years that are selected for plotting.

In the first option there can be more dots than lines, in the second there are the same numbers of dots than lines plotted.

**Comment by signeaa** [comment]
I think it should be possible to see only dots and for selected years. The problem might be then if there should be options for 
1) showing only dots (no lines) for selected years
2) showing only lines (as today) for selected years
3) showing both dots and lines for selected years
And this gives too many options I assume.

So, a simple solution would be to add the option in the "Index" menu: "min/max Sea Ice Extent" which then switches to only-dot-plots and shows the min and max for all the selected years (- that is, using the same clickable years). With the zoom option, it is easily possible to only see all minimas or all maximas. 

What do you think?
