### ISSUE TITLE
revise / confirm what happens when a user chooses "2 years" and "last 5 years"

### ISSUE THREAD

**Issue by TomLav** [metno/sea-ice-index-viz#81]
These two shortcuts were originally made to re-create the static PNGs, thus showing the current year, two (or five) other years, the climatology, and the min/max curves. Today they "only" show the two (or five) additional years, and keep the climatology curves if they are selected from before.

This issue is to keep in mind that we should discuss this, and revise or confirm the behaviour of these two shortcuts.

**Comment by signeaa** [comment]
To be discussed. How do we want to define "last 5 years"? V2.1 is defined as "this year" + 5 recent years before this year (=6 curves in total). Or should it include the 5 recent years, including "this year"?

**Comment by huaracheguarache** [comment]
I've currently revised the code to plot the current year + the preceding 5 years for the "Last 5 years" shortcut, and the current year and the selected two hemisphere dependent years for the "2 years" shortcut.
